### ISSUE TITLE
Feature Request: Skip resolvers

### ISSUE THREAD

**Issue by bboure** [aws/aws-appsync-community#10]
In some cases, it makes no sense to call a resolver at all, for example, when input data is missing.
There should be a way to skip a resolver from being executed and go straight to the response template where we could take some actions.

For example, considering the following query:

````
query {
  getPost(id: 123) {
    id
    name
	userId,
	user {
		name
	}
  }
}

````

If the field `user` needs the `userId` field from `post` to be resolved, but `userId` is null, it makes no sense to call the resolver at all; it would fail anyway.
In the request template for `user`, there should be a way, so that if `$context.source.userId` is null, to skip the resolver and go to the response template where we could handle the error.

**Comment by jbailey2010** [comment]
Hi,

Thanks for the feedback! I've noted this as a feature request with the team.

Thanks,
Jeff

**Comment by buggy** [comment]
If you're trying to stop the resolver from sending the request to the data source then you can already do that by adding the following at the start of the request template.

```
#if ( $util.isNull( $ctx.source.userId ) )
  #return
#endz
```

I think this is the best approach because it's flexible. In response to no `userId` you could respond with `null`, an error or an anonymous user. It also allows you to use complex logic - example: there must be a `userId` and `active` must be `true`.

**Comment by bboure** [comment]
Closing this since `#return` actually does the trick
Thank you @buggy
