### ISSUE TITLE
Feature request - Function / Pipelie Resolver caching

### ISSUE THREAD

**Issue by alecwcp** [aws/aws-appsync-community#132]
The addition of resolver level caching is great https://aws.amazon.com/blogs/mobile/appsync-caching-transactions/

We were hoping to benefit from this, but unfortunately all our resolvers are pipeline resolvers (a design that's come about because we're having to communicate with a REST API, so when the app consuming the GraphQL request wants nested entities we have to use the output of one request to the REST API to inform the next request to it) and that means we can't use the caching within AppSync.

If we could cache at Function level (by some data in `$ctx.stash`, or a new key, like `$ctx.cacheKeys`) then there are times when some of the steps in the pipeline resolver could skip the call to the REST API entirely.

Even having caching available at the top level of the pipeline resolver would be beneficial.

**Comment by itrestian** [comment]
Thank you for the feature request. I will +1 this on your behalf in our backlog.

**Comment by mikel67** [comment]
As a minimum I would like to see pipeline resolvers cached on the boundary. So the net result of all steps will be cached.

For me cache of pipeline resolver results is a +n^2 requirement

Any feedback on plans would be greatly appreciated

**Comment by applyinnovations** [comment]
Is this planned to be implemented soon? I am trying to use the appsync cache to cache the responses from my lambda resolvers. This feature would be greatly appreciated!

**Comment by greg-hornby-roam** [comment]
Any design reason pipeline resolvers don't have caching?

**Comment by vicary** [comment]
Combining `$context.stash` with the AppSync Cache is really a dream come true, I think this supersedes my feature request #179 if implemented.

**Comment by alextriaca** [comment]
This would be an amazing addition for us. A simple example of where this would be useful to us is in a Mutation. The whole mutation obviously can't be cached but functions within a larger pipeline that lookup additional information can be e.g.
* IOT device calls the checkIn(DeviceId, Status) mutation which is backed by a pipeline resolver
* Function 1 looks up the devices associated OrganisationID using the DeviceID in DynamoDB
* Function 2 saves the devices Status along with its DeviceID and OrganisationID to DynamoDB
* Result is returned to the device
It would be useful to cache Function 1 here so that we don't end up overloading DynamoDB and creating a hot key.

**Comment by billfine** [comment]
Support for caching pipeline resolvers is now available. Details, [here](https://aws.amazon.com/blogs/mobile/appsync-pipeline-caching/#:~:text=AppSync%20provides%20two%20types%20of,in%20a%20single%20API%20call.).
