### ISSUE TITLE
Feature request - Trigger a Lambda as a response to a subscription

### ISSUE THREAD

**Issue by alexboulay** [aws/aws-appsync-community#135]
With AppSync, it is easy to link a mutation to a GraphQL subscription. It would be cool to have a Lambda triggered in response to that. Right now, I need to spin up an EC2 instance with a GraphQL client that subscribes to various GraphQL subscriptions.

**Comment by alonsnir** [comment]
You can achieve what you are looking for by using lambda resolver.
"AWS AppSync lets you respond to GraphQL requests by performing operations on your resources. For each GraphQL field you wish to run a query or mutation on, a resolver must be attached in order to communicate with a data source. The communication is typically through parameters or operations that are unique to the data source." 
See [documentation](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference.html)

**Comment by alexboulay** [comment]
@alonsnir  Thanks for your input. Can I use this in addition to DynamoDB as data source? For reference I am using Amplify CLI with @model annotation to create my DynamoDB data source which automatically creates all the VTL resolvers. What you're saying is that I can hook in a Lambda in there?

**Comment by alonsnir** [comment]
@alexboulay yes, multiple data sources are supported. You can add a function using amplify, I don't know how to configure it as a data source using amplify. I would do the following:

1. use amplify as you do currently
2. find a way how to add data source with amplify or configure manually from the console
3. as resolver can be attached to a field and all your fields resolved by DynamoDB, you might end up adding an extra field, lets call it 'lambda_trigger' and specify your lambda function as its resolver. 
4. now when you mutate that 'lambda_trigger' field it should trigger the lambda (which is the only purpose of this field)

another approach would probably be configuring downstream from DynamoDB and route it to lambda. As documented [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.Lambda.html). This is not answering your question, but will trigger lambda on DB updates.

**Comment by jpignata** [comment]
Please let us know if you have any additional questions! Thanks, @alonsnir.
