### ISSUE TITLE
AppSync List API - Database returned more than the allowed response size limit

### ISSUE THREAD

**Issue by stayingcool** [aws/aws-appsync-community#139]
**Issue:**
AppSync List API throws this error and returns a null response:

> "error": {
>             "message": "RDSHttp:{\"message\":\"Database returned more than the allowed response size limit\"}",
>             "type": "400 Bad Request"
>         },

I understand that there is a 1 MB response limit, hence the above error is thrown.

**My requirement** is to be able to **run a report** to pull all the records within a month. My resolver has a simple select statement with a where clause on the date column to filter records for that period. 
I cannot place a limit clause in the select statement as there is already a filter (where clause) to reduce the number of items returned.

**My Environment:**
"react": "^16.12.0",
Amplify CLI version:  4.25.0
"aws-amplify": "^3.3.4"
amplify-serverless using Aurora MySQL (default.aurora5.6)

**What can we do to meet the requirement?**

**Comment by stayingcool** [comment]
Is there anyone who can provide some guidance? This seems to be a show stopper for me to proceed with AppSync.

**Comment by Ricardo1980** [comment]
@stayingcool 
If you don't receive any response from the community or AWS, I recommend you to use a paid plan (like AWS starter/developer or similar) and then use it to send technical questions to AWS engineers.
I use that a lot because very often I don't receive responses in github and in my case, using the paid plan they reply in 24 hours, solving all the problems.
If you don't have money or don't want to spend it, apply for AWS Activate, and use those credits for paying the technical support. That's what I did.
Hope this helps.

BTW, Why are you using  Aurora MySQL (default.aurora5.6) instead of  Aurora MySQL (default.aurora5.7)?

Let me know when you have a solution, I am curious.
BTW, using a lamba function, you may or may not use Client API. Perhaps you should use the second option to bypass that limit. Or perhaps someone from AWS can modify it for you, I don't know.

**Comment by stayingcool** [comment]
@Ricardo1980 -  I thought github is where the developers of AWS are and I'm assuming that I'll get the first hand and direct response. Anyhow thanks, I'll reach out to AWS Support as well!

 Aurora MySQL (default.aurora5.7) was not there I kick started the serverless. It's time to move on to 5.7 then...

**Comment by ahmadizm** [comment]
According to Aurora documentation, there is currently no workaround for the 1MB limit of data returned. The only way to solve this issue is make sure that calls to the Data API return 1 MB of data or less.

**Comment by stayingcool** [comment]
Yes. This was a complete show stopper. 

I have moved on to another GraphQL Engine because of these issues:
- This limitation is poorly documented as "[Schema document size](https://docs.aws.amazon.com/general/latest/gr/appsync.html)". Who in the world will relate that to the API response size? I think it would be better to word it as "API response size limit" or something better.
- Poor documentation and serious lack of features around amplify > appsync> RDS. There is a good amount of doc on DynamoDB!
- No official response from Dev Team on Github (Amplify & Appsync) & Discord
- Support technicians were the most helpful, but they were simply re-directing to the documentation. Btw, after opening issues in GitHub, reaching out in discord you don't expect to open a support ticket!

Not a soul from AWS dev bothered to reply back to the issues in Github or messages in Discord. All the feedback was from the community members and I'm ever thankful to them 👏

Anyhow, I was limping with all the shortcomings of Amplify, Appsync with RDS and this limitation completely derailed my project timelines and led me to refactor my code to move on to another solution.

Please look at this article that describes about many [limitations](https://medium.com/@dadc/aws-appsync-the-unexpected-a430ff7180a3), in my opinion, the overall combination of AppSync with RDS (Amplify) is not even ready for MVP.
