### ISSUE TITLE
Appsync GraphQL page limit

### ISSUE THREAD

**Issue by elusivestudio** [aws/aws-appsync-community#313]
‼️ Critical issue: page limit is broken. I get different results after adding limit and it strangely changes by the limit number.

These are the 3 example at the same time.
<img width="973" alt="Screenshot 2023-08-02 at 16 03 46" src="https://github.com/aws/aws-appsync-community/assets/1245115/a37d648b-fdc1-476c-81d4-2ecc95775dd6">
<img width="973" alt="Screenshot 2023-08-02 at 16 03 58" src="https://github.com/aws/aws-appsync-community/assets/1245115/8cd40442-8f7f-4065-a46e-816484a6a366">
<img width="971" alt="Screenshot 2023-08-02 at 16 04 08" src="https://github.com/aws/aws-appsync-community/assets/1245115/ef833179-fafa-41f3-a3e0-af58196996a4">

**Comment by sashee** [comment]
If you happen to use DynamoDB for this then it might very well because of the combination of filtering along with limiting in the DB query. I wrote an article about this not long ago that looks into a scenario that returns similarly surprising results: https://advancedweb.hu/the-surprising-properties-of-dynamodb-pagination/

**Comment by ATaiIsHere** [comment]
The `limit` parameter in DynamoDB API represents the number of items that will be scanned.

If you can provide the logic of resolver, we can have better idea of what the problem might be.

**Comment by onlybakam** [comment]
@elusivestudio Let us know if you are still experiencing this issue
