### ISSUE TITLE
Subscriptions with nullable args, will break if "nothing"/null is passed.

### ISSUE THREAD

**Issue by potatopotaro** [aws/aws-appsync-community#36]
These docs (https://docs.aws.amazon.com/appsync/latest/devguide/real-time-data.html) claim that our subscriptions can have nullable arguments by omitting (!). For example sake I'll use the doc's example schema:

```
...
subscribeToEventComments(eventId: String): Comment
    @aws_subscribe(mutations: ["commentOnEvent"])
...
```

Using a subscription query, like the one below...

```
subscription SubscribeToEventComments($eventId: String) {
    subscribeToEventComments(eventId: $eventId) {
        ...
    }
}
```

If I instantiate a subscription with an existing/valid `eventId` variable, the subscription works as expected. **However**, if I instantiate a subscription without specifying an `eventId` at all (essentially `null` or `undefined`), the subscription doesn't trigger on any `commentOnEvent` mutations. Both the docs, as well as the behavior of nullable arguments in mutations, suggest that the subscription without an `eventId` specified, should trigger on any and all `commentOnEvent` mutations.

In the above case, where a single argument is being considered, a simple solution to a "global" subscription is to omit any args/parentheses in the subscription query, like so:

```
subscription SubscribeToEventComments {
    subscribeToEventComments {
        ...
    }
}
```

In the case of multiple arguments, especially non-nullable args, the above of course is not usable. All in all, two things come to mind, either:

### 1. This could be considered a bug.
In which case I think more thorough test code should be written for this use case and subscriptions in general. This took me a day and a half to debug, as I thought the issue had to do with the Amplify client library, and not the AppSync service itself. Quite frustrating.

### 2. The docs need to be rewritten + client libraries need adjusting.
The docs led me to believe that Amplify was the problem, and not my AppSync SDL, as I followed the docs very closely. In addition, if this behavior stays as is, this requires us to write many virtually identical subscriptions, to omit the supposedly nullable arguments, e.g...

```
SubscriptionA ...
SubscriptionB ($someId: String) ...
SubscriptionC ($anotherId: String) ...
SubscriptionD ($someId: String, $anotherId: String) ...
```

**Comment by potatopotaro** [comment]
https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/339
https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/241

**Comment by tinnou** [comment]
The question here seems to boil down to the difference in meaning between a `null` field argument value and an inexistent field argument. 

From the sample and your example let’s take the subscription field:
```
type Subscription {
	subscribeToEventComments(eventId: String, content: String): Comment
	@aws_subscribe(mutations: ["commentOnEvent"])
}
```

So the question here is whether the following two queries are equivalent:
__Inexistent field argument__
```
subscribeToEventComments {
	eventId
	commentId
}
```
and 
__null field argument value__
```
subscribeToEventComments(eventId: null) {
	eventId
	commentId
}
```

since I couldn’t find anything in the GraphQL specification pertaining to this, I am going to assume here that this is implementation dependent. 

__Now to go back to your question, does it make sense for these two cases to be semantically different?__
I would argue that yes it does.

Let me explain with an example. Say we have the following schema that resembles the sample event schema. Note that I stripped it down for this example and I added a `Comment.location` field that describes where the comment was sent from. The value could be a set of coordinates or a place.

```
type Comment {
	# The id of the comment's parent event.
	eventId: ID!
	# A unique identifier for the comment.
	commentId: String!
	# The comment's content.
	content: String
        # location where the comment was made 
	location: String
}

type Event {
	id: ID!
	name: String
	where: String
	when: String
	description: String
}

type Mutation {
	commentOnEvent(eventId: ID, location: String, content: String): Comment
}

type Subscription {
	subscribeToEventComments(eventId: String, location: String, content: String): Comment
	@aws_subscribe(mutations: ["commentOnEvent"])
}
```

Now say that I want to get all the comments for a particular event, I would write the following subscription:

```
subscribeToEventComments(eventId: "1") {
	eventId
	commentId
	location
	content
}
```
All is well. Now I would like to get notified of all the comments that have **not** provided a location for a particular event. In the current implementation I can then write:
```
subscribeToEventComments(eventId: "1" location: null) {
	eventId
	commentId
	location
	content
}
```
If we change the subscription implementation so  that a `null` field argument value and an inexistent field are semantically equivalent, then I wouldn’t be able to answer the previous question because the second query is now equivalent to the first query which returns a different set of results.

I agree with you that the docs could explain that behavior in more details and I’ll make sure this gets on our backlog.

**Comment by tinnou** [comment]
Docs had been updated, we added a section titled **Argument null value has meaning** in https://docs.aws.amazon.com/appsync/latest/devguide/real-time-data.html
