### ISSUE TITLE
What is the best way to perform a search across multiple DynamoDB tables in Appsync?

### ISSUE THREAD

**Issue by ShadeAJ1** [aws/aws-appsync-community#42]
I have a question. I am using DynamoDB, AppSync, and Amplify to connect my app and use it with AWS. I want to do a search operation across multiple DynamoDB tables using Appsync's GraphQL API (search input will be given from app). Should I use pipeline resolvers? Can I do this with Batch resolvers? In addition will following [these docs](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-batch.html) for batch resolvers(in my case BatchGet resolvers) help? Please let me know what the best route to follow is and if you need any more info.

**Comment by mikeparisstuff** [comment]
Hey @ShadeAJ1, can you provide more information on what you mean by search? DynamoDB allows you to access a huge data set w/ low latency but its "search" capabilities are somewhat limited. 

You can use `BatchGet` resolvers to get multiple items from multiple tables as long as you know the item keys. Another option is to use pipeline resolvers that will allow you to issue a set of Query or GetItem (or BatchGetItem for that matter) operations against one or more tables before merging results together in the response mapping template of the pipeline resolver itself.

Yet another option is to connect DynamoDB streams to your tables and move information into Elasticsearch where you can perform much more powerful full-text search as long as you the additional cost is acceptable.

If you can provide more details about your access pattern, I can try to help more.

**Comment by ShadeAJ1** [comment]
Hi Micheal. My schema is below.
`type VendorProfile @model {
  id: ID!
  name: String!
  categoryOfService: String!
  img: String!
  locations: [Locations] @connection(name: "Locations")
  ratings: [Ratings] @connection(name: "Ratings")
  services: [Services] @connection(name: "Services")
}

type Locations @model {
  id: ID!
  address: String!
  city: String!
  zipCode: Int!
  vendorLocations: VendorProfile @connection(name: "Locations")
}

type Services @model {
  id: ID!
  serviceName: String!
  imgOfService: String!
  vendorServices: VendorProfile @connection(name: "Services")
  ratings: [Ratings] @connection(name: "ServiceRatings")
}

type Ratings @model {
  id: ID!
  stars: Float!
  comment: String
  customerName: String!
  vendorRatings: VendorProfile @connection(name: "Ratings")
  serviceRatings: Services @connection(name: "ServiceRatings")
}
`

Here I am making a shopping app. Essentially, I have just defined a DynamoDB table for each type. The fields I want to search across are VendorProfile name and Services name.

**Comment by ShadeAJ1** [comment]
Please let me know how to proceed.

**Comment by avlonder** [comment]
> You can use `BatchGet` resolvers to get multiple items from multiple tables as long as you know the item keys. 

I think this is not correct for the multi-table case since you can only specify one data source per resolver... 
I was looking into this because I reached the maximum of 10 functions in my pipeline resolver and I wanted to implement a BatchGetItem function over multiple tables, but it seems impossible

**Comment by Sunac** [comment]
@avlonder actually you can specify it (I moved from a pipeline to a single resolver because I reached that function limit, and could get the tables and keys properly mapped so it was a perfect solution in my case).

Maybe this is not your case so don't mind, but I'll put how I did it, just in case if it could help to overcome your issue too.

I needed this resolver to be attached to a nested field that resolves data from different tables so I already know from a source which tables and ids for each table I need to use, so in the common mapping template, I have that logic to collect ids and pass the table name (defined in a substitution), something like this snippet: 

common mapping template (names are just an example)
> ...$util.qr($tables.put("${SOME_DYNAMODB_TABLE}", $attributes))...
...
#if( !$tables.isEmpty() )
{
    "version" : "2018-05-29",
    "operation" : "BatchGetItem",
    "tables": $util.toJson($tables)
}.....


And define datasource like this (sample names):

> type: AMAZON_DYNAMODB
  name: someName
  description: 'DynamoDB DataSource for something'
  config:
    tableName: empty
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:BatchGetItem
        Resource:
            - { "Fn::Join" : ["", ["arn:aws:dynamodb:${opt:region, self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":table/${file(./sls-yml/sls-env.yml):${self:provider.stage}.DYNAMODB_1}" ] ]  }
            - { "Fn::Join" : ["", ["arn:aws:dynamodb:${opt:region, self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":table/${file(./sls-yml/sls-env.yml):${self:provider.stage}.DYNAMODB_2}" ] ]  }
            - { "Fn::Join" : ["", ["arn:aws:dynamodb:${opt:region, self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":table/${file(./sls-yml/sls-env.yml):${self:provider.stage}.DYNAMODB_3}" ] ]  }
            - { "Fn::Join" : ["", ["arn:aws:dynamodb:${opt:region, self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":table/${file(./sls-yml/sls-env.yml):${self:provider.stage}.DYNAMODB_4}" ] ]  } 

Attach it to each type (resolves nested field as I previously mentioned):
> - dataSource: someName
  type: Some
  field: myField
  request: "common/Common.myField.request.vtl"
  response: "common/Common.myField.response.vtl"
   
 etc. this is just a snippet of how you can define datasource with multiple resources so the table names will be passed from your mapping-template
That is it, but in order to use it, you need to know item keys and map them to a proper table. 

Sorry if I didn't understand your comment properly so this is not what you meant stating that BatchGetItem is not possible over multiple sources.
