### ISSUE TITLE
Scaling Appsync apis to handle concurrent requests

### ISSUE THREAD

**Issue by Jkap7788** [aws/aws-appsync-community#72]
Hi!

I'm hoping someone could shed some light on this topic.

I often see architectural diagrams where a lambda function will be sitting directly behind an appsync resolver (i.e lambda resolver).

However, this architecture seems like it would not be able to handle bursts of concurrent requests.
Appsync has a limit of [1000 queries per second per api](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_appsync) and lambda also has a[ max concurrency limit](https://docs.aws.amazon.com/lambda/latest/dg/limits.html) (depending on what you reserve for this function).

Let's say that I have a mutation as follows:
```
Mutation {
   buyProduct(productId: String!, numProducts: Int!): String
}
```
I have a few questions about this approach:
1) Appsync has a limit of 1000 queries per second, what would happen if 100,000 people decided to all buy a product at once.
2) Lambda has a concurrency limit, what would happen if again 100,000 people decided to all buy a product at once, would the appsync request fail due to throttling?

How would you go about scaling this to handle very high levels of concurrent requests? 

My initial thoughts are instead of using a lambda resolver, use a HTTP resolver and send a message directly to a SQS queue to act as a buffer.
However, would this work seeing as appsync has a limit of 1000 queries per second?

Thanks! Looking forward to some advice on this!

**Comment by undefobj** [comment]
These limits are soft and as the docs say, if you have requirements for them to be increased you can contact support with details on your use case and the service teams can evaluate an increase. Limits are in place not just to protect services but also protect your own account from scenarios such as DDoS, etc.

That being said when looking at your TPS requirements it's important to evaluate the real world implications of these numbers. For instance 100,000 people going to an endpoint is in the worst case scenario going to be a tenth of that traffic due to physics, latency, and even the actions that mobile devices allow - for instance getting 60 FPS on modern devices is about the max you can do. Even if you start to have traffic higher than the configured limit services respond with common messages (such as a 429) to tell the client to backoff and retry.

My suggestion would be to dive deeper into your traffic patterns and potentially run benchmarks with an AWS Solutions Architect rather than try to architect a queueing system like above from the start. Additionally it's best to start small with the defaults and worry about load shedding and other optimizations later when your business is at scale.

**Comment by Jkap7788** [comment]
@undefobj Thank you for the quick and comprehensive response.

You are absolutely right about not optimizing too early and to rather monitor our traffic patterns and only increase capacity once we are hitting a certain traffic threshold. 

Exactly the advice we needed!

In terms of backoff and retry, is their a retry policy documented anywhere for appsync?

Thanks a lot!

**Comment by undefobj** [comment]
No worries. Services will throttle with 429 messages, and if you use the [Amplify clients](https://aws-amplify.github.io) they have exponential backoff and retry build in.

**Comment by Jkap7788** [comment]
@undefobj Thank you for all the help :)
